const TEACHING_CONTENT = {
    "PU1": {
        "3": {
            spelling: ['cow', 'donkey', 'horse', 'spider', 'sheep', 'goat', 'cat', 'chicken', 'dog', 'duck', 'angry', 'funny', 'beautiful', 'happy', 'sad', 'ugly'],
            sight: [["the", "they"], ["they're", "they've got"], ["has", "hasn't"], ["is", "isn't"], ["are", "aren't"], ["have", "haven't"], ["he's", "he's got"], ["I'm", "I've got"], ["it", "it's got"], ["we", "we've got"]],
            grammar: [
                "Rocky's a rooster. He isn't a hen.",
                "Rocky isn't a hen. He's a rooster.",
                "Rocky's got wings, he hasn't got arms.",
                "Rocky hasn't got arms, he's got wings.",
                "Henrietta's a hen. She isn't a rooster.",
                "Henrietta isn't a rooster. She's a hen.",
                "Henrietta's got 2 legs, she hasn't got 4 legs.",
                "Henrietta hasn't got 4 legs, she's got 2 legs.",
                "Harry's a horse. He isn't a donkey.",
                "Harry isn't a donkey. He's a horse.",
                "Harry's got a long tail, he hasn't got a long nose.",
                "Harry hasn't got a long nose, he's got a long tail.",
                "Gracie's a goat. She isn't a sheep.",
                "Gracie isn't a sheep. She's a goat.",
                "Gracie's got 2 eyes, she hasn't got 2 mouths.",
                "Gracie hasn't got 2 mouths, she's got 2 eyes.",
                "Shelly's a sheep. She isn't a goat.",
                "Shelly isn't a goat. She's a sheep.",
                "Shelly's got 4 legs, she hasn't got arms.",
                "Shelly hasn't got arms, she's got 4 legs.",
                "Cameron's small. He isn't big.",
                "Cameron isn't big. He's small.",
                "Cameron's got 4 legs, he hasn't got arms.",
                "Cameron hasn't got arms, he's got 4 legs."
            ]
        },
        "6": {
            spelling: ['bear', 'lorry', 'snake', 'bus', 'car', 'bus stop', 'flower', 'park', 'tiger', 'crocodile', 'motorbike', 'shop', 'zebra', 'lizard', 'giraffe', 'elephant', 'hippo', 'polar bear', 'zoo', 'train', 'tree', 'garden'],
            sight: [["there", "their"], ["there's", "there is"], ["there are", "they are"], ["Are there", "Is there"], ["Is there", "Are there"], ["there isn't", "there aren't"], ["there aren't", "there isn't"]],
            grammar: [
                "Are there any bears? Yes, there are.",
                "Are there any cars? Yes, there are.",
                "Are there any tigers? Yes, there are.",
                "Are there any zebras? Yes, there are.",
                "Are there any hippos? Yes, there are.",
                "Are there any trees? Yes, there are.",
                "Are there any lorries? No, there aren't.",
                "Are there any bus stops? No, there aren't.",
                "Are there any crocodiles? No, there aren't.",
                "Are there any lizards? No, there aren't.",
                "Are there any polar bears? No, there aren't.",
                "Are there any gardens? No, there aren't.",
                "Is there a snake? Yes, there is.",
                "Is there a flower? Yes, there is.",
                "Is there a motorbike? Yes, there is.",
                "Is there a giraffe? Yes, there is.",
                "Is there a zoo? Yes, there is.",
                "Is there a bus? No, there isn't.",
                "Is there a park? No, there isn't.",
                "Is there a shop? No, there isn't.",
                "Is there an elephant? No, there isn't.",
                "Is there a train? No, there isn't.",
                "There aren't any tigers, but there's a zebra.",
                "There isn't a tiger, but there are some zebras.",
                "There are some tigers, but there isn't a zebra.",
                "There's a tiger, but there aren't any zebras.",
                "There aren't any snakes, but there's a lizard.",
                "There isn't a snake, but there are some lizards.",
                "There are some snakes, but there isn't a lizard.",
                "There's a snake, but there aren't any lizards.",
                "There aren't any crocodiles, but there's a hippo.",
                "There isn't a crocodile, but there are some hippos.",
                "There are some crocodiles, but there isn't a hippo.",
                "There's a crocodile, but there aren't any hippos.",
                "There aren't any giraffes, but there's an elephant.",
                "There isn't a giraffe, but there are some elephants.",
                "There are some giraffes, but there isn't an elephant.",
                "There's a giraffe, but there aren't any elephants.",
                "There aren't any cars, but there's a motorbike.",
                "There isn't a car, but there are some motorbikes.",
                "There are some cars, but there isn't a motorbike.",
                "There's a car, but there aren't any motorbikes.",
                "There aren't any buses, but there's a lorry.",
                "There isn't a bus, but there are some lorries.",
                "There are some buses, but there isn't a lorry.",
                "There's a bus, but there aren't any lorries.",
                "There aren't any trains, but there's a bus.",
                "There isn't a train, but there are some buses.",
                "There are some trains, but there isn't a bus.",
                "There's a train, but there aren't any buses.",
                "There aren't any parks, but there's a garden.",
                "There isn't a park, but there are some gardens.",
                "There are some parks, but there isn't a garden.",
                "There's a park, but there aren't any gardens.",
                "There aren't any flowers, but there's a tree.",
                "There isn't a flower, but there are some trees.",
                "There are some flowers, but there isn't a tree.",
                "There's a flower, but there aren't any trees.",
                "There aren't any shops, but there's a bus stop.",
                "There isn't a shop, but there are some bus stops.",
                "There are some shops, but there isn't a bus stop.",
                "There's a shop, but there aren't any bus stops.",
                "There aren't any zoos, but there's a park.",
                "There isn't a zoo, but there are some parks.",
                "There are some zoos, but there isn't a park.",
                "There's a zoo, but there aren't any parks."
            ]
        }
    },
    "PU2": {
        "6": {
            spelling: ["Cloud", "cold", "hot", "rain", "rainbow", "snow", "sunny", "wind", "weather", "cloudy", "windy", "raining", "snowing", "boots", "coat", "scarf", "shorts", "sweater", "T-shirt", "take off", "put on", "wear", "wearing"],
            sight: [['there'], ['was'], ["wasn't"], ['were'], ["weren't"], ['is'], ["isn't"], ['am'], ['am not'], ['are'], ["aren't"]],
            grammar: [
                "Were there any clouds? Yes, there were.",
                "Were there any boots? Yes, there were.",
                "Were there any shorts? Yes, there were.",
                "Were there any clouds? Yes, there were.",
                "Were there any boots? Yes, there were.",
                "Were there any shorts? Yes, there were.",
                "Were there any clouds? No, there weren't.",
                "Were there any boots? No, there weren't.",
                "Were there any shorts? No, there weren't.",
                "Were there any clouds? No, there weren't.",
                "Were there any boots? No, there weren't.",
                "Were there any shorts? No, there weren't.",
                "Was there a rainbow? Yes, there was.",
                "Was there a coat? Yes, there was.",
                "Was there a scarf? Yes, there was.",
                "Was there a sweater? Yes, there was.",
                "Was there a T-shirt? Yes, there was.",
                "Was there a rainbow? No, there wasn't.",
                "Was there a coat? No, there wasn't.",
                "Was there a scarf? No, there wasn't.",
                "Was there a sweater? No, there wasn't.",
                "Was there a T-shirt? No, there wasn't.",
                "There weren't any clouds, but there was a rainbow.",
                "There wasn't a rainbow, but there were some clouds.",
                "There were some clouds, but there wasn't a rainbow.",
                "There was a rainbow, but there weren't any clouds.",
                "There weren't any boots, but there was a coat.",
                "There wasn't a coat, but there were some boots.",
                "There were some boots, but there wasn't a coat.",
                "There was a coat, but there weren't any boots.",
                "There weren't any shorts, but there was a T-shirt.",
                "There wasn't a T-shirt, but there were some shorts.",
                "There were some shorts, but there wasn't a T-shirt.",
                "There was a T-shirt, but there weren't any shorts.",
                "There weren't any clouds, but there was rain.",
                "There wasn't rain, but there were some clouds.",
                "There were some clouds, but there wasn't rain.",
                "There was rain, but there weren't any clouds.",
                "There weren't any boots, but there was a scarf.",
                "There wasn't a scarf, but there were some boots.",
                "There were some boots, but there wasn't a scarf.",
                "There was a scarf, but there weren't any boots.",
                "There weren't any shorts, but there was a sweater.",
                "There wasn't a sweater, but there were some shorts.",
                "There were some shorts, but there wasn't a sweater.",
                "There was a sweater, but there weren't any shorts.",
                "There weren't any clouds, but there was snow.",
                "There wasn't snow, but there were some clouds.",
                "There were some clouds, but there wasn't snow.",
                "There was snow, but there weren't any clouds.",
                "There weren't any boots, but there was a coat.",
                "There wasn't a coat, but there were some boots.",
                "There were some boots, but there wasn't a coat.",
                "There was a coat, but there weren't any boots.",
                "There weren't any clouds, but there was wind.",
                "There wasn't wind, but there were some clouds.",
                "There were some clouds, but there wasn't wind.",
                "There was wind, but there weren't any clouds.",
                "There weren't any shorts, but there was a T-shirt.",
                "There wasn't a T-shirt, but there were some shorts.",
                "There were some shorts, but there wasn't a T-shirt.",
                "There was a T-shirt, but there weren't any shorts.",
                "There weren't any clouds, but there was sunshine.",
                "There wasn't sunshine, but there were some clouds.",
                "There were some clouds, but there wasn't sunshine.",
                "There was sunshine, but there weren't any clouds.",
                "Is it sunny today? Yes, it is.",
                "Is it raining today? No, it isn't.",
                "Is it snowing today? Yes, it is.",
                "Is it windy today? No, it isn't.",
                "Is it cloudy today? Yes, it is.",
                "Is it cloudy today? No, it isn't.",
                "Is it sunny today? No, it isn't.",
                "Was it snowing yesterday? Yes, it was",
                "Was it snowing yesterday? No, it wasn't",
                "Was it sunny yesterday? Yes, it was",
                "Was it sunny yesterday? No, it wasn't",
                "Was it raining yesterday? Yes, it was",
                "Was it raining yesterday? No, it wasn't",
                "Was it windy yesterday? Yes, it was",
                "Was it windy yesterday? No, it wasn't",
                "Was it cloudy yesterday? Yes, it was",
                "Was it cloudy yesterday? No, it wasn't",
                "How's the weather today? It's sunny.",
                "How's the weather today? It's raining.",
                "How's the weather today? It's cloudy.",
                "How's the weather today? It's windy.",
                "How's the weather today? It's snowy.",
                "How was the weather yesterday? It was sunny.",
                "How was the weather yesterday? It was raining.",
                "How was the weather yesterday? It was cloudy.",
                "How was the weather yesterday? It was windy.",
                "How was the weather yesterday? It was snowy.",
                "How's the temperature today? It's cold.",
                "How's the temperature today? It's cool.",
                "How's the temperature today? It's warm.",
                "How's the temperature today? It's hot.",
                "How was the temperature yesterday? It was cold.",
                "How was the temperature yesterday? It was cool.",
                "How was the temperature yesterday? It was warm.",
                "How was the temperature yesterday? It was hot."
            ]
        }
    },
    "PU3": {
        "1": {
            spelling: ['catch', 'dance', 'shout', 'laugh', 'jump', 'hop', 'skip', 'climb', 'dress up', 'hold', 'smile', 'stand', 'midnight', 'half past', 'midday', "o'clock", 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve'],
            sight: [['catch'], ['dance'], ['shout'], ['laugh'], ['jump'], ['hop'], ['skip'], ['climb'], ['dress up'], ['hold'], ['smile'], ['stand'], ['midnight'], ['half past'], ['midday'], ["o'clock"]],
            grammar: [
                "I couldn't catch a ball when I was three.",
                "I could catch a ball when I was five.",
                "He couldn't swim when he was six.",
                "He could swim when he was six.",
                "She couldn't climb trees when she was four.",
                "She could climb trees when she was nine.",
                "I could cook when I was five.",
                "I couldn't cook when I was one.",
                "They could dance when they were four.",
                "They couldn't dance when they were two.",
                "You could jump when you were three.",
                "You couldn't jump when you were two.",
                "We could read when we were six.",
                "We couldn't read when we were two."
            ]
        },
        "5": {
            spelling: ["gold", "silver", "wing", "bright", "light", "spotted", "spots", "striped", "stripes", "plain", "paper", "made of", "trousers", "shirt", "T-shirt", "jacket", "costume", "shoes", "rubber", "wearing", "metal", "paper", "wood", "wool", "card", "glass", "plastic"],
            sight: [["flexible"], ["rigid"], ["heavy"], ["light"], ["smooth"], ["rough"], ["plastic"], ["rubber"], ["gold"], ["silver"], ["wing"], ["bright"], ["light"], ["spotted"], ["spots"], ["striped"], ["stripes"], ["plain"], ["paper"], ["made of"], ["trousers"], ["shirt"], ["T-shirt"], ["jacket"], ["costume"], ["shoes"], ["rubber"], ["wearing"], ["metal"], ["paper"], ["wood"], ["wool"], ["card"], ["glass"], ["plastic"]],
            grammar: [
                "This crown is made of gold. It's heavy", "This table is made of wood. It's rigid", "This ruler is made of plastic. It's flexible", "This house is made of bricks. It's rough", "This newspaper is made of paper. It's light", "This slide is made of metal. It's smooth", "This sweater is made of wool. It's soft", "This scarf is made of wool. It's warm", "These windows are made of glass. They're smooth", "This glass is made of glass. It isn't strong", "This box is made of cardboard. It's light", "This tube is made of cardboard. It's light", "This tire is made of rubber. It's flexible", "These boots are made of rubber. They're flexible"
            ]
        }
    },
    "Think1": {
        "6": {
            spelling: ["cheerful", "confident", "easy-going", "funny", "generous", "helpful", "intelligent", "friendly", "honest", "kind", "patient", "sensible", "boring", "horrible", "jealous", "lazy", "last"],
            sight: [
                ["be", "was"], ["begin", "began"], ["bring", "brought"], ["build", "built"], ["buy", "bought"],
                ["can", "could"], ["catch", "caught"], ["choose", "chose"], ["come", "came"], ["do", "did"],
                ["drive", "drove"], ["eat", "ate"], ["fall", "fell"], ["feel", "felt"], ["find", "found"],
                ["fly", "flew"], ["forget", "forgot"], ["get", "got"], ["go", "went"], ["grow", "grew"],
                ["hear", "heard"], ["hide", "hid"], ["hold", "held"], ["keep", "kept"], ["learn", "learnt"],
                ["let", "let"], ["lose", "lost"], ["make", "made"], ["mean", "meant"], ["meet", "met"],
                ["put", "put"], ["ride", "rode"], ["run", "ran"], ["say", "said"], ["see", "saw"],
                ["sell", "sold"], ["send", "sent"], ["sit", "sat"], ["speak", "spoke"], ["spend", "spent"],
                ["stand", "stood"], ["take", "took"], ["teach", "taught"], ["tell", "told"], ["think", "thought"],
                ["throw", "threw"], ["wake", "woke"], ["write", "wrote"], ["become", "became"], ["break", "broke"],
                ["cost", "cost"], ["cut", "cut"], ["draw", "drew"], ["drink", "drank"], ["give", "gave"],
                ["have", "had"], ["hit", "hit"], ["know", "knew"], ["leave", "left"], ["lend", "lent"],
                ["lie", "lay"], ["pay", "paid"], ["read", "read"], ["show", "showed"], ["sing", "sang"],
                ["sleep", "slept"], ["swim", "swam"], ["understand", "understood"], ["wear", "wore"], ["win", "won"],
                ["answer", "answered"], ["ask", "asked"], ["carry", "carried"], ["change", "changed"],
                ["clean", "cleaned"], ["close", "closed"], ["cook", "cooked"], ["cry", "cried"], ["dance", "danced"],
                ["decide", "decided"], ["drop", "dropped"], ["enjoy", "enjoyed"], ["explain", "explained"],
                ["finish", "finished"], ["happen", "happened"], ["help", "helped"], ["hope", "hoped"],
                ["invite", "invited"], ["jump", "jumped"], ["laugh", "laughed"], ["listen", "listened"],
                ["live", "lived"], ["look", "looked"], ["love", "loved"], ["miss", "missed"], ["move", "moved"],
                ["need", "needed"], ["open", "opened"], ["plan", "planned"], ["play", "played"],
                ["prefer", "preferred"], ["prepare", "prepared"], ["push", "pushed"], ["pull", "pulled"],
                ["rain", "rained"], ["remember", "remembered"], ["return", "returned"], ["save", "saved"],
                ["share", "shared"], ["shop", "shopped"], ["start", "started"], ["stay", "stayed"],
                ["stop", "stopped"], ["study", "studied"], ["talk", "talked"], ["travel", "traveled"],
                ["try", "tried"], ["turn", "turned"], ["use", "used"], ["visit", "visited"], ["wait", "waited"],
                ["walk", "walked"], ["want", "wanted"], ["wash", "washed"], ["watch", "watched"],
                ["work", "worked"], ["worry", "worried"]
            ],
            grammar: [
                "I was sick yesterday.", "The movie began 5 minutes ago.", "He brought a cake yesterday afternoon.", "They built a house last year.",
                "I bought a new bag last week.", "I could not sleep last night.", "He caught the ball 2 seconds ago.", "She chose the red dress yesterday evening.",
                "My friend came to my house yesterday.", "I did my homework 1 hour ago.", "Dad drove the car yesterday morning.", "We ate pizza last night.",
                "The boy fell down 1 minute ago.", "I felt happy yesterday afternoon.", "She found her keys 2 hours ago.", "The bird flew away 5 seconds ago.",
                "I forgot my book yesterday morning.", "He got a gift last month.", "We went to the park last week.", "The tree grew tall last year.",
                "I heard a noise last night.", "The cat hid under the bed 10 minutes ago.", "She held the baby yesterday.", "He kept the money yesterday afternoon.",
                "We learnt English last week.", "Mom let me play outside yesterday.", "I lost my phone 3 days ago.", "She made dinner yesterday evening.",
                "He meant no yesterday.", "I met my teacher 2 days ago.", "He put the pen on the table 1 minute ago.", "I rode my bike last Sunday.",
                "The dog ran fast yesterday afternoon.", "She said hello 5 seconds ago.", "I saw a bird yesterday morning.", "He sold his car last year.",
                "I sent an email 1 hour ago.", "We sat on the chair 5 minutes ago.", "The man spoke to me yesterday.", "I spent 10 dollars yesterday evening.",
                "He stood up 1 second ago.", "She took the bus last week.", "Mr. Smith taught math last year.", "She told me a story last night.",
                "I thought about you yesterday.", "He threw the ball 2 minutes ago.", "I woke up at 7 yesterday morning.", "She wrote a letter last month.",
                "He became a doctor 5 years ago.", "I broke the cup yesterday afternoon.", "The apple cost 1 dollar yesterday.", "She cut the paper 3 minutes ago.",
                "The child drew a picture last night.", "I drank milk yesterday morning.", "He gave me a flower 1 hour ago.", "I had a cold last week.",
                "He hit the ball 5 seconds ago.", "I knew the answer yesterday.", "The bus left 10 minutes ago.", "She lent me a book yesterday afternoon.",
                "The dog lay on the floor last night.", "I paid for the food yesterday evening.", "We read a book last month.", "He showed me his photo yesterday.",
                "She sang a song 2 minutes ago.", "The baby slept well last night.", "We swam in the sea last year.", "I understood the lesson yesterday morning.",
                "She wore a hat last week.", "My team won the game yesterday afternoon.", "He answered the phone 1 minute ago.", "She asked a question yesterday morning.",
                "Dad carried the box 5 minutes ago.", "I changed my clothes yesterday evening.", "Mom cleaned the room yesterday.", "The shop closed 1 hour ago.",
                "We cooked dinner last night.", "The baby cried 2 hours ago.", "They danced at the party last week.", "I decided to go 3 days ago.",
                "He dropped the glass 5 seconds ago.", "We enjoyed the movie yesterday evening.", "The teacher explained the rule yesterday morning.", "I finished my work 30 minutes ago.",
                "The accident happened last year.", "He helped his friend yesterday afternoon.", "I hoped for sun yesterday.", "She invited me to lunch last week.",
                "The cat jumped 2 seconds ago.", "We laughed at the joke yesterday.", "I listened to music last night.", "They lived in China 5 years ago.",
                "She looked at the moon last night.", "I loved that toy 2 years ago.", "He missed the bus yesterday morning.", "We moved house last month.",
                "I needed water 10 minutes ago.", "He opened the window 1 hour ago.", "We planned our holiday last week.", "They played football yesterday afternoon.",
                "I preferred the blue car yesterday.", "Mom prepared lunch 2 hours ago.", "He pushed the door 1 minute ago.", "She pulled the bag yesterday evening.",
                "It rained hard last night.", "I remembered his name 5 seconds ago.", "He returned home yesterday evening.", "I saved money last year.",
                "We shared a pizza last night.", "She shopped for food yesterday morning.", "The game started 10 minutes ago.", "We stayed at home yesterday.",
                "The bus stopped 1 minute ago.", "I studied math last week.", "We talked on the phone 2 hours ago.", "They traveled to Japan last year.",
                "I tried the cake yesterday afternoon.", "The car turned left 5 seconds ago.", "I used a pen yesterday morning.", "We visited Grandma last Sunday.",
                "I waited for you 1 hour ago.", "She walked to the park yesterday.", "I wanted ice cream 5 minutes ago.", "Dad washed the car last week.",
                "I watched TV last night.", "He worked hard yesterday.", "Mom worried about me last night.", "She's cheerful. She smiles all the time.",
                "She's cheerful. She is never sad.", "She's cheerful. She says \"Hello\" to everyone happily.", "He's confident. He knows he is good at English.",
                "He's confident. He is not shy when he speaks.", "He's confident. He stands up tall and speaks strictly.", "He's easy-going. He is very relaxed.",
                "He's easy-going. He never gets angry about small things.", "He's easy-going. He says \"No problem\" a lot.", "He's funny. He tells great jokes.",
                "He's funny. He makes all his friends laugh.", "He's funny. He is like a clown in the class.", "She's generous. She buys presents for all her friends.",
                "She's generous. She shares her lunch with me.", "She's generous. She likes to give things to people.", "He's helpful. He helps his mum clean the house.",
                "She's helpful. She helps her brother with his homework.", "He's helpful. He carries the heavy bags for the teacher.", "She's intelligent. She learns very fast.",
                "She's intelligent. She gets 100% on her tests.", "She's intelligent. She knows the answer to every question.", "He's friendly. He talks to new students.",
                "She's friendly. She likes to play with everyone.", "He's friendly. Everyone likes him because he is nice.", "He's honest. He never tells a lie.",
                "He's honest. He always tells the truth.", "He's honest. If he breaks a window, he says \"I did it.\"", "She's kind. She is very nice to animals.",
                "She's kind. She helps people when they are sad.", "She's kind. She has a good heart.", "He's patient. He can wait for a long time.",
                "He's patient. He doesn't get angry when the bus is late.", "He's patient. He helps me slowly and doesn't say \"Hurry up!\"", "She's sensible. It is cold, so she wears a coat.",
                "He's sensible. He does his homework before he plays games.", "She's sensible. She doesn't do dangerous things.", "He's boring. I want to sleep when he talks.",
                "He's boring. He never does fun things.", "He's boring. His stories are not interesting.", "He's horrible. He kicks the dog.",
                "He's horrible. He shouts at his little sister.", "He's horrible. He is a very bad person.", "He's jealous. He wants my new toy.",
                "She's jealous. She is angry because the teacher likes me.", "He's jealous. He wants what his friend has.", "He's lazy. He stays in bed all day.",
                "He's lazy. He doesn't want to work or study.", "He's lazy. He never cleans his room."
            ]
        }
    }
};

const AVAILABLE_CONTENT = {
    "PU1": [3, 6],
    "PU2": [6],
    "PU3": [1, 5],
    "Think1": [6]
};
