name: inject-test
on:
  push:
    branches: [main]
jobs:
  t:
    runs-on: ubuntu-latest
    steps:
      - name: Inject client app config
        if: ${{ secrets.APP_CLIENT_KEY != '' }}
        shell: bash
        run: |
          printf '{"APP_API_KEY":"%s"}\n' "${{ secrets.APP_CLIENT_KEY }}" > app-config.json
